### ISSUE TITLE
Missing Inventory RE2 Remake

### ISSUE THREAD

**Issue by brharr** [SpeedrunTooling/SRTPluginManager#37]
I just ran the latest builds using this project having run your stand alone files for a long time and this is awesome. GREAT JOB. As a developer myself for almost 4 decades, great work. 

I have been primarily focusing on RE2 Remake recently and I just tried this SRT manager against that and was using the DirectX Overlay. The inventory was missing, but everything else showed just fine. The image from your installation instructions leads me to believe that they should be showing and I didn't see any option in the Widgets section where I could turn it on or off. 

Any help that you can provide would be be greatly appreciated.

**Comment by Squirrelies** [comment]
Tracking this in the appropriate repo @ https://github.com/SpeedrunTooling/SRTPluginUIRE2DirectXOverlay/issues/3
