### ISSUE TITLE
Not working after new update

### ISSUE THREAD

**Issue by BoogiePoot** [SpeedrunTooling/SRTPluginManager#38]
Hello. The new update for re2 and re3 remake caused the SRT tool to it work. I'm running the dx11 version (non RT) please update. Love this tool

**Comment by Squirrelies** [comment]
Please open issues at the respective repos for those plugins if this is still an issue.

https://github.com/SpeedrunTooling/SRTPluginProviderRE2
https://github.com/SpeedrunTooling/SRTPluginProviderRE3
